import streamlit as st
import pandas as pd
from src.ui.utils import load_config, read_json, artifact_exists
from src.ui.components.artifact_status import artifact_panel, dependency_warning
from src.ui.components.controls import run_stage_button
from src.ui.components.tables import show_df, kpi_row
from src.ui.components.text import render_page_header, render_section_title, render_caption
from src.optimization.runner import run_optimization


def _load_result(solver_name: str):
    return read_json(f"solver_result_{solver_name.lower()}.json")


def _show_result(data: dict, solver_name: str) -> None:
    if data is None:
        st.info(f"No result found for {solver_name}.")
        return

    kpi_row({
        "Status":        data.get("status", "—").upper(),
        "Objective":     f"${data.get('objective_value', 0):,.0f}",
        "Realized Cost": f"${data.get('total_cost', 0):,.0f}",
        "Service Level": f"{data.get('service_level', 0):.1%}",
        "Unmet Demand":  f"{data.get('unmet_demand_teu', 0):,.1f} TEU",
        "Solve Time":    f"{data.get('solve_time_seconds', 0):.3f}s",
        "Total Moves":   str(len(data.get("decisions", []))),
    })

    decisions = data.get("decisions", [])
    if decisions:
        st.markdown("<br>", unsafe_allow_html=True)
        render_section_title("Operational Allocations")
        render_caption(f"Sequential container repositioning orders generated by the {solver_name} engine.")
        show_df(pd.DataFrame(decisions), max_rows=100)

    diag = data.get("diagnostics", {})
    if diag:
        with st.expander("Computational Diagnostics"):
            st.json(diag)


def render():
    render_page_header(
        title_en="Stage 8 — Optimization Solvers",
        title_fa="مرحله ۸ — اجرای الگوریتم‌های بهینه‌سازی",
        desc_en="This stage executes the chosen operational solvers (Heuristic or MILP) against the Structured Problem. It resolves supply-demand disparities while strictly adhering to the configured multi-modal operational limits and financial constraints.",
        desc_fa="در این مرحله، موتورهای بهینه‌سازی (ریاضی یا ابتکاری) حل مسئله را آغاز می‌کنند تا با رعایت کامل محدودیت‌های شبکه‌های لجستیکی و بودجه، ارزان‌ترین و سریع‌ترین مسیرها را برای برطرف کردن عدم تعادل کانتینرها بیابند."
    )

    cfg = load_config()
    col_run, col_refresh = st.columns([2, 1])
    with col_run:
        run_stage_button("optimization", fn=run_optimization, config=cfg)
    with col_refresh:
        if st.button("🔄 Refresh View", key="refresh_opt"):
            st.cache_data.clear()

    if dependency_warning("optimization"):
        return

    artifact_panel(["solver_result_heuristic.json", "solver_result_milp.json"])

    if _load_result("heuristic") is None and _load_result("milp") is None:
        st.info("Wait... Run the Optimization Solvers stage above to generate transportation plans.")
        return

    st.markdown("<br>", unsafe_allow_html=True)
    render_section_title("Algorithm Output Views")
    tabs = st.tabs(["🔧 Heuristic Engine", "🔬 MILP Math Engine"])
    with tabs[0]:
        _show_result(_load_result("heuristic"), "Heuristic")
    with tabs[1]:
        _show_result(_load_result("milp"), "MILP")
